//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionPoint
    {
        public string CollectionPointCode { get; set; }
        public string CollectionPointName { get; set; }
        public string CollectionTime { get; set; }
        public string StoreClerk { get; set; }
    }
}
