//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentList
    {
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> TelephoneNo { get; set; }
        public Nullable<int> FaxNo { get; set; }
        public string HeadId { get; set; }
        public string CollectionPoint { get; set; }
        public string RepresentativeId { get; set; }
    }
}
