//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDBContext : DbContext
    {
        public ModelDBContext()
            : base("name=ModelDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<DepartmentList> DepartmentLists { get; set; }
        public virtual DbSet<DisbursementListDetail> DisbursementListDetails { get; set; }
        public virtual DbSet<DisbursementList> DisbursementLists { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<OutstandingList> OutstandingLists { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<RequisitionFormDetail> RequisitionFormDetails { get; set; }
        public virtual DbSet<RequisitionForm> RequisitionForms { get; set; }
        public virtual DbSet<StationeryCatalog> StationeryCatalogs { get; set; }
        public virtual DbSet<StationeryRetrievalFormDetail> StationeryRetrievalFormDetails { get; set; }
        public virtual DbSet<StationeryRetrievalForm> StationeryRetrievalForms { get; set; }
        public virtual DbSet<StockAdjustmentVoucherDetail> StockAdjustmentVoucherDetails { get; set; }
        public virtual DbSet<StockAdjustmentVoucher> StockAdjustmentVouchers { get; set; }
        public virtual DbSet<StoreClerk> StoreClerks { get; set; }
        public virtual DbSet<StoreManager> StoreManagers { get; set; }
        public virtual DbSet<StoreSupervisor> StoreSupervisors { get; set; }
        public virtual DbSet<SupplierList> SupplierLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
