//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingList
    {
        public string OutstandingListNumber { get; set; }
        public string RequisitionFormNumber { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> Balance { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> Needed { get; set; }
        public string PONumber { get; set; }
        public string Status { get; set; }
    
        public virtual DepartmentList DepartmentList { get; set; }
        public virtual RequisitionForm RequisitionForm { get; set; }
        public virtual StationeryCatalog StationeryCatalog { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
