//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public string PODetailsNumber { get; set; }
        public string PONumber { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public Nullable<double> ReceivedValue { get; set; }
        public string Remarks { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual StationeryCatalog StationeryCatalog { get; set; }
    }
}
