//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.OutstandingLists = new HashSet<OutstandingList>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public string PONumber { get; set; }
        public string SupplierCode { get; set; }
        public string DeliverTo { get; set; }
        public string Attention { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> SupplyByDate { get; set; }
        public string OrderedBy { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ReceivedGoodsFormNo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<double> ReceivedValue { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public Nullable<double> PurchaseValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutstandingList> OutstandingLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual StoreClerk StoreClerk { get; set; }
        public virtual StoreClerk StoreClerk1 { get; set; }
        public virtual StoreSupervisor StoreSupervisor { get; set; }
        public virtual SupplierList SupplierList { get; set; }
    }
}
