//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryCatalog
    {
        public string ItemNumber { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string BinNumber { get; set; }
        public Nullable<double> Price { get; set; }
        public string SupplierCode1 { get; set; }
        public string SupplierCode2 { get; set; }
        public string SupplierCode3 { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
