//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationeryCatalog()
        {
            this.DisbursementListDetails = new HashSet<DisbursementListDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.RequisitionFormDetails = new HashSet<RequisitionFormDetail>();
            this.StationeryRetrievalFormDetails = new HashSet<StationeryRetrievalFormDetail>();
            this.StockAdjustmentVoucherDetails = new HashSet<StockAdjustmentVoucherDetail>();
        }
    
        public string ItemNumber { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string BinNumber { get; set; }
        public Nullable<double> Price { get; set; }
        public string SupplierCode1 { get; set; }
        public string SupplierCode2 { get; set; }
        public string SupplierCode3 { get; set; }
        public Nullable<int> Balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementListDetail> DisbursementListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionFormDetail> RequisitionFormDetails { get; set; }
        public virtual SupplierList SupplierList { get; set; }
        public virtual SupplierList SupplierList1 { get; set; }
        public virtual SupplierList SupplierList2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationeryRetrievalFormDetail> StationeryRetrievalFormDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustmentVoucherDetail> StockAdjustmentVoucherDetails { get; set; }
    }
}
