//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryRetrievalFormDetail
    {
        public string FormDetailsNumber { get; set; }
        public string FormNumber { get; set; }
        public string ItemNumber { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> Needed { get; set; }
        public Nullable<int> Actual { get; set; }
    
        public virtual DepartmentList DepartmentList { get; set; }
        public virtual StationeryCatalog StationeryCatalog { get; set; }
        public virtual StationeryRetrievalForm StationeryRetrievalForm { get; set; }
    }
}
