//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryRetrievalFormDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationeryRetrievalFormDetail()
        {
            this.OutstandingLists = new HashSet<OutstandingList>();
        }
    
        public string FormDetailsNumber { get; set; }
        public string FormNumber { get; set; }
        public string ItemNumber { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> Needed { get; set; }
        public Nullable<int> Actual { get; set; }
    
        public virtual DepartmentList DepartmentList { get; set; }
        public virtual StationeryCatalog StationeryCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutstandingList> OutstandingLists { get; set; }
        public virtual StationeryRetrievalForm StationeryRetrievalForm { get; set; }
    }
}
