//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustmentVoucherDetail
    {
        public string AdjustmentDetailsNumber { get; set; }
        public string AdjustmentVoucherNumber { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> QuantityAdjusted { get; set; }
        public string Reason { get; set; }
    }
}
