//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stationeryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierList
    {
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string GSTNo { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public Nullable<int> FaxNo { get; set; }
        public string Address { get; set; }
    }
}
